# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0003_auto_20160928_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
