# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0004_auto_20160928_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scribble.Room'),
        ),
    ]
