# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0005_auto_20160928_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_list', to='scribble.Player'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(default='pic/not_found.jpg', upload_to='pic/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='scribble.Room'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scribble.Artwork'),
        ),
        migrations.AlterField(
            model_name='like',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='scribble.Artwork'),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='scribble.Room'),
        ),
    ]
